// Generated at 2026-Sep-05 21:02:09
//
rsd_dd_Pk b1_1_mu0;
rsd_dd_Pk b1_1_mu2;
rsd_dd_Pk b1_1_mu4;
rsd_dd_Pk b1_1_mu6;
rsd_dd_Pk b1_1_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_mu8);
payload->emplace(std::make_pair("b1_1", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_mu0, b1_1_mu2, b1_1_mu4, b1_1_mu6, b1_1_mu8}));

rsd_dd_Pk b1_1_b1_1_mu0;
rsd_dd_Pk b1_1_b1_1_mu2;
rsd_dd_Pk b1_1_b1_1_mu4;
rsd_dd_Pk b1_1_b1_1_mu6;
rsd_dd_Pk b1_1_b1_1_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_1_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_1_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_1_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_1_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_1_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_1_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_1_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_1_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_1_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_1_mu8);
payload->emplace(std::make_pair("b1_1_b1_1", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b1_1_mu0, b1_1_b1_1_mu2, b1_1_b1_1_mu4, b1_1_b1_1_mu6, b1_1_b1_1_mu8}));

rsd_dd_Pk b1_1_b1_2_mu0;
rsd_dd_Pk b1_1_b1_2_mu2;
rsd_dd_Pk b1_1_b1_2_mu4;
rsd_dd_Pk b1_1_b1_2_mu6;
rsd_dd_Pk b1_1_b1_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_2_mu8);
payload->emplace(std::make_pair("b1_1_b1_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b1_2_mu0, b1_1_b1_2_mu2, b1_1_b1_2_mu4, b1_1_b1_2_mu6, b1_1_b1_2_mu8}));

rsd_dd_Pk b1_1_b1_3_mu0;
rsd_dd_Pk b1_1_b1_3_mu2;
rsd_dd_Pk b1_1_b1_3_mu4;
rsd_dd_Pk b1_1_b1_3_mu6;
rsd_dd_Pk b1_1_b1_3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b1_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b1_3_mu8);
payload->emplace(std::make_pair("b1_1_b1_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b1_3_mu0, b1_1_b1_3_mu2, b1_1_b1_3_mu4, b1_1_b1_3_mu6, b1_1_b1_3_mu8}));

rsd_dd_Pk b1_1_b2_2_mu0;
rsd_dd_Pk b1_1_b2_2_mu2;
rsd_dd_Pk b1_1_b2_2_mu4;
rsd_dd_Pk b1_1_b2_2_mu6;
rsd_dd_Pk b1_1_b2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_2_mu8);
payload->emplace(std::make_pair("b1_1_b2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b2_2_mu0, b1_1_b2_2_mu2, b1_1_b2_2_mu4, b1_1_b2_2_mu6, b1_1_b2_2_mu8}));

rsd_dd_Pk b1_1_b2_3_mu0;
rsd_dd_Pk b1_1_b2_3_mu2;
rsd_dd_Pk b1_1_b2_3_mu4;
rsd_dd_Pk b1_1_b2_3_mu6;
rsd_dd_Pk b1_1_b2_3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b2_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b2_3_mu8);
payload->emplace(std::make_pair("b1_1_b2_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b2_3_mu0, b1_1_b2_3_mu2, b1_1_b2_3_mu4, b1_1_b2_3_mu6, b1_1_b2_3_mu8}));

rsd_dd_Pk b1_1_b3_mu0;
rsd_dd_Pk b1_1_b3_mu2;
rsd_dd_Pk b1_1_b3_mu4;
rsd_dd_Pk b1_1_b3_mu6;
rsd_dd_Pk b1_1_b3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_b3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_b3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_b3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_b3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_b3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_b3_mu8);
payload->emplace(std::make_pair("b1_1_b3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_b3_mu0, b1_1_b3_mu2, b1_1_b3_mu4, b1_1_b3_mu6, b1_1_b3_mu8}));

rsd_dd_Pk b1_1_bG2_2_mu0;
rsd_dd_Pk b1_1_bG2_2_mu2;
rsd_dd_Pk b1_1_bG2_2_mu4;
rsd_dd_Pk b1_1_bG2_2_mu6;
rsd_dd_Pk b1_1_bG2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_2_mu8);
payload->emplace(std::make_pair("b1_1_bG2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_bG2_2_mu0, b1_1_bG2_2_mu2, b1_1_bG2_2_mu4, b1_1_bG2_2_mu6, b1_1_bG2_2_mu8}));

rsd_dd_Pk b1_1_bG2_3_mu0;
rsd_dd_Pk b1_1_bG2_3_mu2;
rsd_dd_Pk b1_1_bG2_3_mu4;
rsd_dd_Pk b1_1_bG2_3_mu6;
rsd_dd_Pk b1_1_bG2_3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_bG2_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bG2_3_mu8);
payload->emplace(std::make_pair("b1_1_bG2_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_bG2_3_mu0, b1_1_bG2_3_mu2, b1_1_bG2_3_mu4, b1_1_bG2_3_mu6, b1_1_bG2_3_mu8}));

rsd_dd_Pk b1_1_bGamma3_mu0;
rsd_dd_Pk b1_1_bGamma3_mu2;
rsd_dd_Pk b1_1_bGamma3_mu4;
rsd_dd_Pk b1_1_bGamma3_mu6;
rsd_dd_Pk b1_1_bGamma3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_bGamma3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bGamma3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_bGamma3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bGamma3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_bGamma3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bGamma3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_bGamma3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bGamma3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_bGamma3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bGamma3_mu8);
payload->emplace(std::make_pair("b1_1_bGamma3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_bGamma3_mu0, b1_1_bGamma3_mu2, b1_1_bGamma3_mu4, b1_1_bGamma3_mu6, b1_1_bGamma3_mu8}));

rsd_dd_Pk b1_1_bdG2_mu0;
rsd_dd_Pk b1_1_bdG2_mu2;
rsd_dd_Pk b1_1_bdG2_mu4;
rsd_dd_Pk b1_1_bdG2_mu6;
rsd_dd_Pk b1_1_bdG2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_1_bdG2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bdG2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_1_bdG2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bdG2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_1_bdG2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bdG2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_1_bdG2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bdG2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_1_bdG2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_1_bdG2_mu8);
payload->emplace(std::make_pair("b1_1_bdG2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_1_bdG2_mu0, b1_1_bdG2_mu2, b1_1_bdG2_mu4, b1_1_bdG2_mu6, b1_1_bdG2_mu8}));

rsd_dd_Pk b1_2_mu0;
rsd_dd_Pk b1_2_mu2;
rsd_dd_Pk b1_2_mu4;
rsd_dd_Pk b1_2_mu6;
rsd_dd_Pk b1_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_mu8);
payload->emplace(std::make_pair("b1_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_2_mu0, b1_2_mu2, b1_2_mu4, b1_2_mu6, b1_2_mu8}));

rsd_dd_Pk b1_2_b1_2_mu0;
rsd_dd_Pk b1_2_b1_2_mu2;
rsd_dd_Pk b1_2_b1_2_mu4;
rsd_dd_Pk b1_2_b1_2_mu6;
rsd_dd_Pk b1_2_b1_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_2_b1_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b1_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_2_b1_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b1_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_2_b1_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b1_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_2_b1_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b1_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_2_b1_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b1_2_mu8);
payload->emplace(std::make_pair("b1_2_b1_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_2_b1_2_mu0, b1_2_b1_2_mu2, b1_2_b1_2_mu4, b1_2_b1_2_mu6, b1_2_b1_2_mu8}));

rsd_dd_Pk b1_2_b2_2_mu0;
rsd_dd_Pk b1_2_b2_2_mu2;
rsd_dd_Pk b1_2_b2_2_mu4;
rsd_dd_Pk b1_2_b2_2_mu6;
rsd_dd_Pk b1_2_b2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_2_b2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_2_b2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_2_b2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_2_b2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_2_b2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_b2_2_mu8);
payload->emplace(std::make_pair("b1_2_b2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_2_b2_2_mu0, b1_2_b2_2_mu2, b1_2_b2_2_mu4, b1_2_b2_2_mu6, b1_2_b2_2_mu8}));

rsd_dd_Pk b1_2_bG2_2_mu0;
rsd_dd_Pk b1_2_bG2_2_mu2;
rsd_dd_Pk b1_2_bG2_2_mu4;
rsd_dd_Pk b1_2_bG2_2_mu6;
rsd_dd_Pk b1_2_bG2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_2_bG2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_bG2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_2_bG2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_bG2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_2_bG2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_bG2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_2_bG2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_bG2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_2_bG2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_2_bG2_2_mu8);
payload->emplace(std::make_pair("b1_2_bG2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_2_bG2_2_mu0, b1_2_bG2_2_mu2, b1_2_bG2_2_mu4, b1_2_bG2_2_mu6, b1_2_bG2_2_mu8}));

rsd_dd_Pk b1_3_mu0;
rsd_dd_Pk b1_3_mu2;
rsd_dd_Pk b1_3_mu4;
rsd_dd_Pk b1_3_mu6;
rsd_dd_Pk b1_3_mu8;
find_impl::read_dd_rsd_Pk(db, "b1_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_3_mu0);
find_impl::read_dd_rsd_Pk(db, "b1_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_3_mu2);
find_impl::read_dd_rsd_Pk(db, "b1_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_3_mu4);
find_impl::read_dd_rsd_Pk(db, "b1_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_3_mu6);
find_impl::read_dd_rsd_Pk(db, "b1_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b1_3_mu8);
payload->emplace(std::make_pair("b1_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b1_3_mu0, b1_3_mu2, b1_3_mu4, b1_3_mu6, b1_3_mu8}));

rsd_dd_Pk b2_2_mu0;
rsd_dd_Pk b2_2_mu2;
rsd_dd_Pk b2_2_mu4;
rsd_dd_Pk b2_2_mu6;
rsd_dd_Pk b2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_mu8);
payload->emplace(std::make_pair("b2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b2_2_mu0, b2_2_mu2, b2_2_mu4, b2_2_mu6, b2_2_mu8}));

rsd_dd_Pk b2_2_b2_2_mu0;
rsd_dd_Pk b2_2_b2_2_mu2;
rsd_dd_Pk b2_2_b2_2_mu4;
rsd_dd_Pk b2_2_b2_2_mu6;
rsd_dd_Pk b2_2_b2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b2_2_b2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_b2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b2_2_b2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_b2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b2_2_b2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_b2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b2_2_b2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_b2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b2_2_b2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_b2_2_mu8);
payload->emplace(std::make_pair("b2_2_b2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b2_2_b2_2_mu0, b2_2_b2_2_mu2, b2_2_b2_2_mu4, b2_2_b2_2_mu6, b2_2_b2_2_mu8}));

rsd_dd_Pk b2_2_bG2_2_mu0;
rsd_dd_Pk b2_2_bG2_2_mu2;
rsd_dd_Pk b2_2_bG2_2_mu4;
rsd_dd_Pk b2_2_bG2_2_mu6;
rsd_dd_Pk b2_2_bG2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "b2_2_bG2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_bG2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "b2_2_bG2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_bG2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "b2_2_bG2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_bG2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "b2_2_bG2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_bG2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "b2_2_bG2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_2_bG2_2_mu8);
payload->emplace(std::make_pair("b2_2_bG2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b2_2_bG2_2_mu0, b2_2_bG2_2_mu2, b2_2_bG2_2_mu4, b2_2_bG2_2_mu6, b2_2_bG2_2_mu8}));

rsd_dd_Pk b2_3_mu0;
rsd_dd_Pk b2_3_mu2;
rsd_dd_Pk b2_3_mu4;
rsd_dd_Pk b2_3_mu6;
rsd_dd_Pk b2_3_mu8;
find_impl::read_dd_rsd_Pk(db, "b2_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_3_mu0);
find_impl::read_dd_rsd_Pk(db, "b2_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_3_mu2);
find_impl::read_dd_rsd_Pk(db, "b2_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_3_mu4);
find_impl::read_dd_rsd_Pk(db, "b2_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_3_mu6);
find_impl::read_dd_rsd_Pk(db, "b2_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b2_3_mu8);
payload->emplace(std::make_pair("b2_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b2_3_mu0, b2_3_mu2, b2_3_mu4, b2_3_mu6, b2_3_mu8}));

rsd_dd_Pk b3_mu0;
rsd_dd_Pk b3_mu2;
rsd_dd_Pk b3_mu4;
rsd_dd_Pk b3_mu6;
rsd_dd_Pk b3_mu8;
find_impl::read_dd_rsd_Pk(db, "b3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b3_mu0);
find_impl::read_dd_rsd_Pk(db, "b3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b3_mu2);
find_impl::read_dd_rsd_Pk(db, "b3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b3_mu4);
find_impl::read_dd_rsd_Pk(db, "b3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b3_mu6);
find_impl::read_dd_rsd_Pk(db, "b3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, b3_mu8);
payload->emplace(std::make_pair("b3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, b3_mu0, b3_mu2, b3_mu4, b3_mu6, b3_mu8}));

rsd_dd_Pk bG2_2_mu0;
rsd_dd_Pk bG2_2_mu2;
rsd_dd_Pk bG2_2_mu4;
rsd_dd_Pk bG2_2_mu6;
rsd_dd_Pk bG2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "bG2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "bG2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "bG2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "bG2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "bG2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_mu8);
payload->emplace(std::make_pair("bG2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, bG2_2_mu0, bG2_2_mu2, bG2_2_mu4, bG2_2_mu6, bG2_2_mu8}));

rsd_dd_Pk bG2_2_bG2_2_mu0;
rsd_dd_Pk bG2_2_bG2_2_mu2;
rsd_dd_Pk bG2_2_bG2_2_mu4;
rsd_dd_Pk bG2_2_bG2_2_mu6;
rsd_dd_Pk bG2_2_bG2_2_mu8;
find_impl::read_dd_rsd_Pk(db, "bG2_2_bG2_2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_bG2_2_mu0);
find_impl::read_dd_rsd_Pk(db, "bG2_2_bG2_2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_bG2_2_mu2);
find_impl::read_dd_rsd_Pk(db, "bG2_2_bG2_2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_bG2_2_mu4);
find_impl::read_dd_rsd_Pk(db, "bG2_2_bG2_2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_bG2_2_mu6);
find_impl::read_dd_rsd_Pk(db, "bG2_2_bG2_2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_2_bG2_2_mu8);
payload->emplace(std::make_pair("bG2_2_bG2_2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, bG2_2_bG2_2_mu0, bG2_2_bG2_2_mu2, bG2_2_bG2_2_mu4, bG2_2_bG2_2_mu6, bG2_2_bG2_2_mu8}));

rsd_dd_Pk bG2_3_mu0;
rsd_dd_Pk bG2_3_mu2;
rsd_dd_Pk bG2_3_mu4;
rsd_dd_Pk bG2_3_mu6;
rsd_dd_Pk bG2_3_mu8;
find_impl::read_dd_rsd_Pk(db, "bG2_3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_3_mu0);
find_impl::read_dd_rsd_Pk(db, "bG2_3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_3_mu2);
find_impl::read_dd_rsd_Pk(db, "bG2_3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_3_mu4);
find_impl::read_dd_rsd_Pk(db, "bG2_3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_3_mu6);
find_impl::read_dd_rsd_Pk(db, "bG2_3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bG2_3_mu8);
payload->emplace(std::make_pair("bG2_3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, bG2_3_mu0, bG2_3_mu2, bG2_3_mu4, bG2_3_mu6, bG2_3_mu8}));

rsd_dd_Pk bGamma3_mu0;
rsd_dd_Pk bGamma3_mu2;
rsd_dd_Pk bGamma3_mu4;
rsd_dd_Pk bGamma3_mu6;
rsd_dd_Pk bGamma3_mu8;
find_impl::read_dd_rsd_Pk(db, "bGamma3_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bGamma3_mu0);
find_impl::read_dd_rsd_Pk(db, "bGamma3_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bGamma3_mu2);
find_impl::read_dd_rsd_Pk(db, "bGamma3_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bGamma3_mu4);
find_impl::read_dd_rsd_Pk(db, "bGamma3_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bGamma3_mu6);
find_impl::read_dd_rsd_Pk(db, "bGamma3_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bGamma3_mu8);
payload->emplace(std::make_pair("bGamma3", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, bGamma3_mu0, bGamma3_mu2, bGamma3_mu4, bGamma3_mu6, bGamma3_mu8}));

rsd_dd_Pk bdG2_mu0;
rsd_dd_Pk bdG2_mu2;
rsd_dd_Pk bdG2_mu4;
rsd_dd_Pk bdG2_mu6;
rsd_dd_Pk bdG2_mu8;
find_impl::read_dd_rsd_Pk(db, "bdG2_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bdG2_mu0);
find_impl::read_dd_rsd_Pk(db, "bdG2_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bdG2_mu2);
find_impl::read_dd_rsd_Pk(db, "bdG2_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bdG2_mu4);
find_impl::read_dd_rsd_Pk(db, "bdG2_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bdG2_mu6);
find_impl::read_dd_rsd_Pk(db, "bdG2_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, bdG2_mu8);
payload->emplace(std::make_pair("bdG2", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, bdG2_mu0, bdG2_mu2, bdG2_mu4, bdG2_mu6, bdG2_mu8}));

rsd_dd_Pk nobias_mu0;
rsd_dd_Pk nobias_mu2;
rsd_dd_Pk nobias_mu4;
rsd_dd_Pk nobias_mu6;
rsd_dd_Pk nobias_mu8;
find_impl::read_dd_rsd_Pk(db, "nobias_mu0", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, nobias_mu0);
find_impl::read_dd_rsd_Pk(db, "nobias_mu2", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, nobias_mu2);
find_impl::read_dd_rsd_Pk(db, "nobias_mu4", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, nobias_mu4);
find_impl::read_dd_rsd_Pk(db, "nobias_mu6", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, nobias_mu6);
find_impl::read_dd_rsd_Pk(db, "nobias_mu8", model, growth_params, loop_params, k, z, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, nobias_mu8);
payload->emplace(std::make_pair("nobias", oneloop_Pk{k, growth_params, loop_params, init_Pk_lin, final_Pk_lin, IR_cutoff, UV_cutoff, z, nobias_mu0, nobias_mu2, nobias_mu4, nobias_mu6, nobias_mu8}));

