// Generated at 2026-Sep-05 21:02:09
//
std::set<unsigned int> b1_1_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_1_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_1_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_1_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_1_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_1_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_3_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_3_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_3_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_3_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b1_3_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_3_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_3_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_3_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_3_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b2_3_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_b3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b3_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_b3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b3_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_b3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b3_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_b3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b3_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_b3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_b3_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_3_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_3_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_3_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_3_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bG2_3_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bGamma3_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bGamma3_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bGamma3_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bGamma3_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bGamma3_mu8", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bdG2_mu0", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bdG2_mu2", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bdG2_mu4", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bdG2_mu6", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_1_bdG2_mu8", z_table, record, missing);
std::set<unsigned int> b1_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b1_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b1_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b1_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b1_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b1_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b2_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b2_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b2_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b2_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_b2_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_bG2_2_mu0", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_bG2_2_mu2", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_bG2_2_mu4", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_bG2_2_mu6", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_2_bG2_2_mu8", z_table, record, missing);
std::set<unsigned int> b1_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_3_mu0", z_table, record, missing);
std::set<unsigned int> b1_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_3_mu2", z_table, record, missing);
std::set<unsigned int> b1_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_3_mu4", z_table, record, missing);
std::set<unsigned int> b1_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_3_mu6", z_table, record, missing);
std::set<unsigned int> b1_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b1_3_mu8", z_table, record, missing);
std::set<unsigned int> b2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_mu0", z_table, record, missing);
std::set<unsigned int> b2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_mu2", z_table, record, missing);
std::set<unsigned int> b2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_mu4", z_table, record, missing);
std::set<unsigned int> b2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_mu6", z_table, record, missing);
std::set<unsigned int> b2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_mu8", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_b2_2_mu0", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_b2_2_mu2", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_b2_2_mu4", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_b2_2_mu6", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_b2_2_mu8", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_bG2_2_mu0", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_bG2_2_mu2", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_bG2_2_mu4", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_bG2_2_mu6", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_2_bG2_2_mu8", z_table, record, missing);
std::set<unsigned int> b2_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_3_mu0", z_table, record, missing);
std::set<unsigned int> b2_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_3_mu2", z_table, record, missing);
std::set<unsigned int> b2_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_3_mu4", z_table, record, missing);
std::set<unsigned int> b2_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_3_mu6", z_table, record, missing);
std::set<unsigned int> b2_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b2_3_mu8", z_table, record, missing);
std::set<unsigned int> b3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b3_mu0", z_table, record, missing);
std::set<unsigned int> b3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b3_mu2", z_table, record, missing);
std::set<unsigned int> b3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b3_mu4", z_table, record, missing);
std::set<unsigned int> b3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b3_mu6", z_table, record, missing);
std::set<unsigned int> b3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "b3_mu8", z_table, record, missing);
std::set<unsigned int> bG2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_mu0", z_table, record, missing);
std::set<unsigned int> bG2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_mu2", z_table, record, missing);
std::set<unsigned int> bG2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_mu4", z_table, record, missing);
std::set<unsigned int> bG2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_mu6", z_table, record, missing);
std::set<unsigned int> bG2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_mu8", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_bG2_2_mu0", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_bG2_2_mu2", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_bG2_2_mu4", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_bG2_2_mu6", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_2_bG2_2_mu8", z_table, record, missing);
std::set<unsigned int> bG2_3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_3_mu0", z_table, record, missing);
std::set<unsigned int> bG2_3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_3_mu2", z_table, record, missing);
std::set<unsigned int> bG2_3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_3_mu4", z_table, record, missing);
std::set<unsigned int> bG2_3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_3_mu6", z_table, record, missing);
std::set<unsigned int> bG2_3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bG2_3_mu8", z_table, record, missing);
std::set<unsigned int> bGamma3_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bGamma3_mu0", z_table, record, missing);
std::set<unsigned int> bGamma3_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bGamma3_mu2", z_table, record, missing);
std::set<unsigned int> bGamma3_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bGamma3_mu4", z_table, record, missing);
std::set<unsigned int> bGamma3_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bGamma3_mu6", z_table, record, missing);
std::set<unsigned int> bGamma3_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bGamma3_mu8", z_table, record, missing);
std::set<unsigned int> bdG2_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bdG2_mu0", z_table, record, missing);
std::set<unsigned int> bdG2_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bdG2_mu2", z_table, record, missing);
std::set<unsigned int> bdG2_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bdG2_mu4", z_table, record, missing);
std::set<unsigned int> bdG2_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bdG2_mu6", z_table, record, missing);
std::set<unsigned int> bdG2_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "bdG2_mu8", z_table, record, missing);
std::set<unsigned int> nobias_mu0 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "nobias_mu0", z_table, record, missing);
std::set<unsigned int> nobias_mu2 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "nobias_mu2", z_table, record, missing);
std::set<unsigned int> nobias_mu4 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "nobias_mu4", z_table, record, missing);
std::set<unsigned int> nobias_mu6 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "nobias_mu6", z_table, record, missing);
std::set<unsigned int> nobias_mu8 = update_missing_one_loop_Pk(db, model, growth_params, loop_params, init_Pk, final_Pk, "nobias_mu8", z_table, record, missing);

drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_mu0", record, b1_1_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_mu2", record, b1_1_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_mu4", record, b1_1_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_mu6", record, b1_1_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_mu8", record, b1_1_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_1_mu0", record, b1_1_b1_1_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_1_mu2", record, b1_1_b1_1_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_1_mu4", record, b1_1_b1_1_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_1_mu6", record, b1_1_b1_1_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_1_mu8", record, b1_1_b1_1_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_2_mu0", record, b1_1_b1_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_2_mu2", record, b1_1_b1_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_2_mu4", record, b1_1_b1_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_2_mu6", record, b1_1_b1_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_2_mu8", record, b1_1_b1_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_3_mu0", record, b1_1_b1_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_3_mu2", record, b1_1_b1_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_3_mu4", record, b1_1_b1_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_3_mu6", record, b1_1_b1_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b1_3_mu8", record, b1_1_b1_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_2_mu0", record, b1_1_b2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_2_mu2", record, b1_1_b2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_2_mu4", record, b1_1_b2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_2_mu6", record, b1_1_b2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_2_mu8", record, b1_1_b2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_3_mu0", record, b1_1_b2_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_3_mu2", record, b1_1_b2_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_3_mu4", record, b1_1_b2_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_3_mu6", record, b1_1_b2_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b2_3_mu8", record, b1_1_b2_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b3_mu0", record, b1_1_b3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b3_mu2", record, b1_1_b3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b3_mu4", record, b1_1_b3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b3_mu6", record, b1_1_b3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_b3_mu8", record, b1_1_b3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_2_mu0", record, b1_1_bG2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_2_mu2", record, b1_1_bG2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_2_mu4", record, b1_1_bG2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_2_mu6", record, b1_1_bG2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_2_mu8", record, b1_1_bG2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_3_mu0", record, b1_1_bG2_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_3_mu2", record, b1_1_bG2_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_3_mu4", record, b1_1_bG2_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_3_mu6", record, b1_1_bG2_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bG2_3_mu8", record, b1_1_bG2_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bGamma3_mu0", record, b1_1_bGamma3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bGamma3_mu2", record, b1_1_bGamma3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bGamma3_mu4", record, b1_1_bGamma3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bGamma3_mu6", record, b1_1_bGamma3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bGamma3_mu8", record, b1_1_bGamma3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bdG2_mu0", record, b1_1_bdG2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bdG2_mu2", record, b1_1_bdG2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bdG2_mu4", record, b1_1_bdG2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bdG2_mu6", record, b1_1_bdG2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_1_bdG2_mu8", record, b1_1_bdG2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_mu0", record, b1_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_mu2", record, b1_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_mu4", record, b1_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_mu6", record, b1_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_mu8", record, b1_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b1_2_mu0", record, b1_2_b1_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b1_2_mu2", record, b1_2_b1_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b1_2_mu4", record, b1_2_b1_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b1_2_mu6", record, b1_2_b1_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b1_2_mu8", record, b1_2_b1_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b2_2_mu0", record, b1_2_b2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b2_2_mu2", record, b1_2_b2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b2_2_mu4", record, b1_2_b2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b2_2_mu6", record, b1_2_b2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_b2_2_mu8", record, b1_2_b2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_bG2_2_mu0", record, b1_2_bG2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_bG2_2_mu2", record, b1_2_bG2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_bG2_2_mu4", record, b1_2_bG2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_bG2_2_mu6", record, b1_2_bG2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_2_bG2_2_mu8", record, b1_2_bG2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_3_mu0", record, b1_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_3_mu2", record, b1_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_3_mu4", record, b1_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_3_mu6", record, b1_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b1_3_mu8", record, b1_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_mu0", record, b2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_mu2", record, b2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_mu4", record, b2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_mu6", record, b2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_mu8", record, b2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_b2_2_mu0", record, b2_2_b2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_b2_2_mu2", record, b2_2_b2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_b2_2_mu4", record, b2_2_b2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_b2_2_mu6", record, b2_2_b2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_b2_2_mu8", record, b2_2_b2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_bG2_2_mu0", record, b2_2_bG2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_bG2_2_mu2", record, b2_2_bG2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_bG2_2_mu4", record, b2_2_bG2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_bG2_2_mu6", record, b2_2_bG2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_2_bG2_2_mu8", record, b2_2_bG2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_3_mu0", record, b2_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_3_mu2", record, b2_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_3_mu4", record, b2_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_3_mu6", record, b2_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b2_3_mu8", record, b2_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b3_mu0", record, b3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b3_mu2", record, b3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b3_mu4", record, b3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b3_mu6", record, b3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "b3_mu8", record, b3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_mu0", record, bG2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_mu2", record, bG2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_mu4", record, bG2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_mu6", record, bG2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_mu8", record, bG2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_bG2_2_mu0", record, bG2_2_bG2_2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_bG2_2_mu2", record, bG2_2_bG2_2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_bG2_2_mu4", record, bG2_2_bG2_2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_bG2_2_mu6", record, bG2_2_bG2_2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_2_bG2_2_mu8", record, bG2_2_bG2_2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_3_mu0", record, bG2_3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_3_mu2", record, bG2_3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_3_mu4", record, bG2_3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_3_mu6", record, bG2_3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bG2_3_mu8", record, bG2_3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bGamma3_mu0", record, bGamma3_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bGamma3_mu2", record, bGamma3_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bGamma3_mu4", record, bGamma3_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bGamma3_mu6", record, bGamma3_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bGamma3_mu8", record, bGamma3_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bdG2_mu0", record, bdG2_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bdG2_mu2", record, bdG2_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bdG2_mu4", record, bdG2_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bdG2_mu6", record, bdG2_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "bdG2_mu8", record, bdG2_mu8, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "nobias_mu0", record, nobias_mu0, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "nobias_mu2", record, nobias_mu2, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "nobias_mu4", record, nobias_mu4, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "nobias_mu6", record, nobias_mu6, missing);
drop_inconsistent_redshifts(db, model, init_Pk, growth_params, loop_params, final_Pk, "nobias_mu8", record, nobias_mu8, missing);
