// Generated at 2026-Sep-05 21:02:09
//
std::set<unsigned int> b1_1_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P0", z_table, record, missing);
std::set<unsigned int> b1_1_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P2", z_table, record, missing);
std::set<unsigned int> b1_1_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_1_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b1_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b2_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P4", z_table, record, missing);
std::set<unsigned int> b1_1_b3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P0", z_table, record, missing);
std::set<unsigned int> b1_1_b3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P2", z_table, record, missing);
std::set<unsigned int> b1_1_b3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P4", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P0", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P2", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P4", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P0", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P2", z_table, record, missing);
std::set<unsigned int> b1_1_bG2_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P4", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P0", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P2", z_table, record, missing);
std::set<unsigned int> b1_1_bGamma3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P4", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P0", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P2", z_table, record, missing);
std::set<unsigned int> b1_1_bdG2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P4", z_table, record, missing);
std::set<unsigned int> b1_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P0", z_table, record, missing);
std::set<unsigned int> b1_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P2", z_table, record, missing);
std::set<unsigned int> b1_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P4", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P0", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P2", z_table, record, missing);
std::set<unsigned int> b1_2_b1_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P4", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P0", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P2", z_table, record, missing);
std::set<unsigned int> b1_2_b2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P4", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P0", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P2", z_table, record, missing);
std::set<unsigned int> b1_2_bG2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P4", z_table, record, missing);
std::set<unsigned int> b1_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P0", z_table, record, missing);
std::set<unsigned int> b1_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P2", z_table, record, missing);
std::set<unsigned int> b1_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P4", z_table, record, missing);
std::set<unsigned int> b2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P0", z_table, record, missing);
std::set<unsigned int> b2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P2", z_table, record, missing);
std::set<unsigned int> b2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P4", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P0", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P2", z_table, record, missing);
std::set<unsigned int> b2_2_b2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P4", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P0", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P2", z_table, record, missing);
std::set<unsigned int> b2_2_bG2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P4", z_table, record, missing);
std::set<unsigned int> b2_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P0", z_table, record, missing);
std::set<unsigned int> b2_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P2", z_table, record, missing);
std::set<unsigned int> b2_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P4", z_table, record, missing);
std::set<unsigned int> b3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P0", z_table, record, missing);
std::set<unsigned int> b3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P2", z_table, record, missing);
std::set<unsigned int> b3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P4", z_table, record, missing);
std::set<unsigned int> bG2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P0", z_table, record, missing);
std::set<unsigned int> bG2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P2", z_table, record, missing);
std::set<unsigned int> bG2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P4", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P0", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P2", z_table, record, missing);
std::set<unsigned int> bG2_2_bG2_2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P4", z_table, record, missing);
std::set<unsigned int> bG2_3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P0", z_table, record, missing);
std::set<unsigned int> bG2_3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P2", z_table, record, missing);
std::set<unsigned int> bG2_3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P4", z_table, record, missing);
std::set<unsigned int> bGamma3_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P0", z_table, record, missing);
std::set<unsigned int> bGamma3_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P2", z_table, record, missing);
std::set<unsigned int> bGamma3_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P4", z_table, record, missing);
std::set<unsigned int> bdG2_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P0", z_table, record, missing);
std::set<unsigned int> bdG2_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P2", z_table, record, missing);
std::set<unsigned int> bdG2_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P4", z_table, record, missing);
std::set<unsigned int> nobias_P0 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P0", z_table, record, missing);
std::set<unsigned int> nobias_P2 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P2", z_table, record, missing);
std::set<unsigned int> nobias_P4 = update_missing_multipole_Pk(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P4", z_table, record, missing);

drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P0", record, b1_1_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P2", record, b1_1_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_P4", record, b1_1_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P0", record, b1_1_b1_1_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P2", record, b1_1_b1_1_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_1_P4", record, b1_1_b1_1_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P0", record, b1_1_b1_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P2", record, b1_1_b1_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_2_P4", record, b1_1_b1_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P0", record, b1_1_b1_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P2", record, b1_1_b1_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b1_3_P4", record, b1_1_b1_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P0", record, b1_1_b2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P2", record, b1_1_b2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_2_P4", record, b1_1_b2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P0", record, b1_1_b2_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P2", record, b1_1_b2_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b2_3_P4", record, b1_1_b2_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P0", record, b1_1_b3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P2", record, b1_1_b3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_b3_P4", record, b1_1_b3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P0", record, b1_1_bG2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P2", record, b1_1_bG2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_2_P4", record, b1_1_bG2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P0", record, b1_1_bG2_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P2", record, b1_1_bG2_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bG2_3_P4", record, b1_1_bG2_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P0", record, b1_1_bGamma3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P2", record, b1_1_bGamma3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bGamma3_P4", record, b1_1_bGamma3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P0", record, b1_1_bdG2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P2", record, b1_1_bdG2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_1_bdG2_P4", record, b1_1_bdG2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P0", record, b1_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P2", record, b1_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_P4", record, b1_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P0", record, b1_2_b1_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P2", record, b1_2_b1_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b1_2_P4", record, b1_2_b1_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P0", record, b1_2_b2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P2", record, b1_2_b2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_b2_2_P4", record, b1_2_b2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P0", record, b1_2_bG2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P2", record, b1_2_bG2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_2_bG2_2_P4", record, b1_2_bG2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P0", record, b1_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P2", record, b1_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b1_3_P4", record, b1_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P0", record, b2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P2", record, b2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_P4", record, b2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P0", record, b2_2_b2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P2", record, b2_2_b2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_b2_2_P4", record, b2_2_b2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P0", record, b2_2_bG2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P2", record, b2_2_bG2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_2_bG2_2_P4", record, b2_2_bG2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P0", record, b2_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P2", record, b2_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b2_3_P4", record, b2_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P0", record, b3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P2", record, b3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "b3_P4", record, b3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P0", record, bG2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P2", record, bG2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_P4", record, bG2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P0", record, bG2_2_bG2_2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P2", record, bG2_2_bG2_2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_2_bG2_2_P4", record, bG2_2_bG2_2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P0", record, bG2_3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P2", record, bG2_3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bG2_3_P4", record, bG2_3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P0", record, bGamma3_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P2", record, bGamma3_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bGamma3_P4", record, bGamma3_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P0", record, bdG2_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P2", record, bdG2_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "bdG2_P4", record, bdG2_P4, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P0", record, nobias_P0, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P2", record, nobias_P2, missing);
drop_inconsistent_redshifts(db, model, growth_params, loop_params, XY_params, init_Pk, final_Pk, "nobias_P4", record, nobias_P4, missing);
