#!/usr/bin/env python3
"""validation/canonical_form.py -- parse and canonicalise emitted LSSEFT-analytic kernels.

This module is the *parsing layer* shared by the validation tooling. It knows how to:

  * extract the per-kernel ``double value_ = ...;`` and ``double Wick_ = ...;`` expressions out
    of an emitted ``autogenerated/kernel_integrands.cpp`` (:func:`extract_kernels`);
  * rewrite the emitted C++ into something SymPy can read (:func:`cpp_to_python`);
  * parse that with **exact rational literals** (:func:`parse_exact`), so that ``-(2.0/5.0)``
    becomes ``Rational(-2, 5)`` and not a binary float.  Parsing with default float literals
    produces 1e-16 residuals that look like real algebraic disagreements and are not;
  * reduce to a single cancelled rational function with ``cancel(together(.))``
    (:func:`canonical`).

It also canonicalises the **print order** of the ``** COUNTERTERM MAP`` section of a run log
(:func:`canonical_counterterm_map`, CLI ``--counterterm-map``), which is the only way to compare
that artefact between runs: it is default-printed rather than ``csrc``-printed, so GiNaC's
per-process operand ordering varies inside each line and sorting the lines achieves nothing.
Measured: the canonicalised form is a single md5 across all five runs of the non-determinism study
*and* the ``--auto-symmetrize`` run.

Run directly for the ``--dedup`` diagnostic:

    validation/canonical_form.py --dedup path/to/autogenerated

which reports how many of the emitted kernels are algebraically distinct, keyed jointly on the
canonicalised ``value_`` expression and the raw ``Wick_`` string.  This reproduces the
feasibility study's Sec. 3.4 result (101 emitted, 95 distinct, 6 duplicate pairs).

It is a *diagnostic*, not a gate: the duplicates are issue I-05 and are explicitly out of scope
for this campaign.  ``--dedup`` therefore exits 0 whatever it finds, unless ``--expect`` is
given.

See also: validation/compare_autogenerated.py (the actual regression gate),
validation/README.md, prompts/pre-python-migration-fixes/02-oracle-harness-and-baseline.md.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Dict, List, NamedTuple, Tuple

import sympy
from sympy.parsing.sympy_parser import (
    parse_expr,
    rationalize,
    standard_transformations,
)

# ---------------------------------------------------------------------------------------------
# free variables of an emitted integrand
#
# backends/LSSEFT.cpp introduces exactly three: k_ (external momentum), q_ (loop momentum) and
# z_ (the cosine of the angle between them).  See backends/LSSEFT.cpp:698-712, where
# subs_map = { {q0, q_}, {x, z_}, {k, k_} } is built and then handed to print_integrand() /
# print_WickProduct().
# ---------------------------------------------------------------------------------------------

K, Q, Z = sympy.symbols("k_ q_ z_", positive=None)
FREE_SYMBOLS = (K, Q, Z)

#: The surrogate power spectrum.  Left unevaluated by this module; compare_autogenerated.py
#: substitutes a concrete rational function for it.
PK = sympy.Function("Pk")

_TRANSFORMS = standard_transformations + (rationalize,)

_LOCAL_DICT = {"k_": K, "q_": Q, "z_": Z, "Pk": PK, "pow": sympy.Pow}


# ---------------------------------------------------------------------------------------------
# extraction
# ---------------------------------------------------------------------------------------------

#: Opening line of an emitted kernel, e.g.
#:   static int ker100_integrand(const int* ndim_, const cubareal x_[], ...)
_KERNEL_RE = re.compile(r"^static\s+int\s+(?P<name>ker\w+)_integrand\s*\(", re.MULTILINE)

_VALUE_RE = re.compile(r"^\s*double\s+value_\s*=\s*(?P<expr>.*);\s*$", re.MULTILINE)
_WICK_RE = re.compile(r"^\s*double\s+Wick_\s*=\s*(?P<expr>.*);\s*$", re.MULTILINE)


class Kernel(NamedTuple):
    """One emitted integrand, as text."""

    name: str  #: e.g. "ker100"
    value: str  #: the raw C++ right-hand side of `double value_ = ...;`
    wick: str  #: the raw C++ right-hand side of `double Wick_ = ...;`


def extract_kernels(path: str) -> List[Kernel]:
    """Extract every (name, value_, Wick_) triple from an emitted kernel_integrands.cpp.

    `path` may be the file itself or the `autogenerated/` directory containing it.

    Raises ValueError if a kernel body does not contain exactly one `value_` and one `Wick_`,
    because that would mean the emitter's shape has changed and the rest of this tooling is no
    longer parsing what it thinks it is parsing.
    """

    path = _resolve(path)
    with open(path, "r", encoding="utf-8") as handle:
        src = handle.read()

    starts = [(m.start(), m.group("name")) for m in _KERNEL_RE.finditer(src)]
    if not starts:
        raise ValueError(f"{path}: no `static int kerNNN_integrand(` definitions found")

    bounds = [s for s, _ in starts] + [len(src)]

    kernels: List[Kernel] = []
    for index, (_, name) in enumerate(starts):
        body = src[bounds[index] : bounds[index + 1]]

        values = _VALUE_RE.findall(body)
        wicks = _WICK_RE.findall(body)
        if len(values) != 1 or len(wicks) != 1:
            raise ValueError(
                f"{path}: kernel {name} has {len(values)} `double value_` and "
                f"{len(wicks)} `double Wick_` lines; expected exactly 1 of each"
            )

        kernels.append(Kernel(name=name, value=values[0], wick=wicks[0]))

    return kernels


def _resolve(path: str) -> str:
    """Accept either an autogenerated/ directory or a kernel_integrands.cpp path."""

    if os.path.isdir(path):
        return os.path.join(path, "kernel_integrands.cpp")
    return path


def compute_names(path: str) -> List[str]:
    """The sorted, deduplicated set of `compute_*` names in an emitted tree.

    `path` may be the `autogenerated/` directory or `Pk_expressions.cpp` directly.  This is the
    second half of the "is this the same output?" question -- the integrand signatures cover the
    kernels, the compute_* names cover the assembly layer above them.
    """

    if os.path.isdir(path):
        path = os.path.join(path, "Pk_expressions.cpp")
    with open(path, "r", encoding="utf-8") as handle:
        src = handle.read()
    return sorted(set(re.findall(r"compute_[A-Za-z0-9_]*", src)))


# ---------------------------------------------------------------------------------------------
# C++ -> Python
# ---------------------------------------------------------------------------------------------

# Order matters: Mpc3 must be rewritten before Mpc, since "Mpc" is a prefix of "Mpc3".
#
# The unit factors are dropped by rewriting them to 1 rather than by deleting the text, so that
# the surrounding division stays syntactically intact:
#
#   data_->Pk((expr)/Mpc_units::Mpc) / Mpc_units::Mpc3   ->   Pk((expr)/1) / 1
#
# This is a *functional* comparison of dimensionless shapes; the units cancel identically on
# both sides of any comparison, so dropping them cannot mask a disagreement.
_REWRITES: Tuple[Tuple[str, str], ...] = (
    ("data_->Pk", "Pk"),
    ("Mpc_units::Mpc3", "1"),
    ("Mpc_units::Mpc", "1"),
    ("std::pow", "pow"),
)

#: Every token the emitter is known to produce inside a value_ / Wick_ expression, after the
#: rewrites above have been applied.  Anything else means the emitter grew a construct this
#: tooling has not been taught, and we must fail loudly rather than silently mis-parse.
_KNOWN_TOKENS = frozenset({"k_", "q_", "z_", "pow", "Pk"})

_TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_:]*")


def cpp_to_python(expr: str) -> str:
    """Rewrite one emitted C++ expression into Python/SymPy source text.

    Raises ValueError on any identifier this tooling does not recognise.
    """

    out = expr
    for needle, replacement in _REWRITES:
        out = out.replace(needle, replacement)

    unknown = sorted({t for t in _TOKEN_RE.findall(out) if t not in _KNOWN_TOKENS})
    if unknown:
        raise ValueError(
            "unrecognised identifier(s) in emitted expression: "
            + ", ".join(unknown)
            + "\n  -- validation/canonical_form.py must be taught this construct; "
            "see _REWRITES / _KNOWN_TOKENS.\n  expression: "
            + expr[:400]
        )

    return out


def parse_exact(expr: str) -> sympy.Expr:
    """Parse one emitted C++ expression into SymPy with **exact rational literals**.

    `1.0/8.0` becomes `Rational(1, 8)`, `(1.0/2.0)` as a `pow` exponent becomes a genuine square
    root, and `-2.0` becomes `Integer(-2)`.  Nothing is a binary float, so nothing carries
    1e-16 noise into a later comparison.
    """

    return parse_expr(
        cpp_to_python(expr), transformations=_TRANSFORMS, local_dict=_LOCAL_DICT
    )


def parse_exact_no_floats(expr: str) -> sympy.Expr:
    """`parse_exact`, additionally asserting that no Float survived the parse."""

    parsed = parse_exact(expr)
    floats = parsed.atoms(sympy.Float)
    if floats:
        raise ValueError(
            f"parse left {len(floats)} Float literal(s) in the expression "
            f"(e.g. {sorted(floats, key=str)[:3]}); the rationalize transformation "
            "did not fire as expected"
        )
    return parsed


# ---------------------------------------------------------------------------------------------
# canonical form
# ---------------------------------------------------------------------------------------------


def canonical(expr: sympy.Expr) -> sympy.Expr:
    """Reduce to a single cancelled rational function: `cancel(together(expr))`.

    `together` puts the expression over a common denominator; `cancel` then reduces the
    resulting numerator/denominator pair to lowest terms.  Two rational functions that are
    algebraically equal reach the same normal form under this, which is what makes it usable as
    a dedup key.  It is *not* a complete decision procedure for expressions containing
    `sqrt(...)`, which is why the Wick product is keyed on its string rather than canonicalised.
    """

    return sympy.cancel(sympy.together(expr))


# ---------------------------------------------------------------------------------------------
# canonicalising the counterterm map
#
# The `** COUNTERTERM MAP` section of a run log is *default*-printed by GiNaC, not `csrc`-printed,
# and its operand ordering therefore varies between processes: the five-run study measured four
# distinct md5s of the sorted-lines form (validation/NONDETERMINISM.md Sec. 3.2). Sorting the
# lines does not help, because the variation is *inside* each line.
#
# The functions below canonicalise each right-hand side textually, by recursively sorting the
# operands of every top-level `*` and every `+`/`-` term list and normalising leading signs. That
# is enough for the *observed* variation, which is purely commutative reordering -- measured: it
# collapses all five canonical runs and the --auto-symmetrize run to a single md5.
#
# What it deliberately does NOT do: any algebra. It will not see through distribution, `2*a` vs
# `a+a`, a factor moved in or out of a bracket, or a change of exponent form. That is the point --
# a real change to the counterterm map must still show up as a difference. It is a *print-order*
# canonicaliser, not a normal form.
# ---------------------------------------------------------------------------------------------

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

_CT_HEADER = "** COUNTERTERM MAP"

#: The right-hand sides that need canonicalising, e.g. "   -> mu^2 = <expr>".
_CT_ENTRY_RE = re.compile(r"^(?P<label>   -> mu\^\d+ = )(?P<expr>.*)$")

_MAX_CANON_DEPTH = 12


def _split_top(expr: str, sep: str) -> List[str]:
    """Split `expr` on `sep` at bracket depth zero."""

    out: List[str] = []
    depth = 0
    current = ""
    for char in expr:
        if char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        if char == sep and depth == 0:
            out.append(current)
            current = ""
        else:
            current += char
    out.append(current)
    return out


def _split_terms(expr: str) -> List[Tuple[str, str]]:
    """Split `expr` into (sign, term) pairs at depth-zero `+` / `-`.

    A `+`/`-` is a term separator only when it is not the first character and not preceded by an
    operator -- that is what distinguishes the binary minus of `a-b` from the unary minus of
    `a^(-2)`, `(-3)` or a leading `-a`.
    """

    out: List[Tuple[str, str]] = []
    depth = 0
    current = ""
    sign = "+"
    for index, char in enumerate(expr):
        if char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        if depth == 0 and char in "+-":
            if index == 0:
                sign = char
                continue
            if expr[index - 1] not in "*^(+-,":
                out.append((sign, current))
                sign = char
                current = ""
                continue
        current += char
    out.append((sign, current))
    return out


def canonical_printed_expr(expr: str, depth: int = 0) -> str:
    """Canonicalise the *print order* of one default-printed GiNaC expression.

    Recursively sorts the operands of commutative `*` and `+`/`-` and normalises leading signs.
    Purely textual: no algebra, no re-parsing, no SymPy.
    """

    if depth > _MAX_CANON_DEPTH:
        return expr

    expr = expr.strip()

    terms = _split_terms(expr)
    if len(terms) > 1:
        parts = sorted(
            sign + canonical_printed_expr(term, depth + 1) for sign, term in terms
        )
        joined = "".join(parts)
        return f"({joined})" if depth else joined

    sign, body = terms[0]
    prefix = "-" if sign == "-" else ""

    factors = _split_top(body, "*")
    if len(factors) > 1:
        return prefix + "*".join(
            sorted(canonical_printed_expr(f, depth + 1) for f in factors)
        )

    if body.startswith("(") and body.endswith(")"):
        return prefix + "(" + canonical_printed_expr(body[1:-1], depth + 1) + ")"

    return prefix + body


def canonical_counterterm_map(log_path: str) -> List[str]:
    """Extract and canonicalise the `** COUNTERTERM MAP` section of a run log.

    ANSI colour codes are stripped, each entry's right-hand side is print-order canonicalised,
    and the resulting lines are sorted. The result is comparable between runs despite I-01.
    """

    with open(log_path, "r", encoding="utf-8", errors="replace") as handle:
        text = _ANSI_RE.sub("", handle.read())

    if _CT_HEADER not in text:
        raise ValueError(
            f"{log_path}: no '{_CT_HEADER}' section -- was the run invoked with --counterterms?"
        )

    lines = text[text.index(_CT_HEADER) :].split("\n")

    out: List[str] = []
    for line in lines:
        match = _CT_ENTRY_RE.match(line)
        out.append(
            match.group("label") + canonical_printed_expr(match.group("expr"))
            if match
            else line
        )

    return sorted(out)


def canonical_key(kernel: Kernel) -> Tuple[str, str]:
    """The dedup key for one kernel: (canonicalised value_, raw Wick_ string).

    Keyed *jointly* on the Wick product, per the study's Sec. 3.4 method: two kernels with the
    same integrand but different Wick products are genuinely different kernels.
    """

    return (sympy.srepr(canonical(parse_exact_no_floats(kernel.value))), kernel.wick)


# ---------------------------------------------------------------------------------------------
# --dedup
# ---------------------------------------------------------------------------------------------


def dedup_report(path: str, verbose: bool = True) -> Tuple[int, int, List[List[str]]]:
    """Report (emitted, distinct, duplicate-groups) for an emitted tree.

    Returns the number of kernels emitted, the number of algebraically distinct
    (value_, Wick_) keys, and the list of duplicate groups as lists of kerNNN names.
    """

    kernels = extract_kernels(path)

    buckets: Dict[Tuple[str, str], List[str]] = {}
    for index, kernel in enumerate(kernels, start=1):
        if verbose and (index % 20 == 0 or index == len(kernels)):
            print(
                f"  canonicalising {index}/{len(kernels)} ...", file=sys.stderr, flush=True
            )
        buckets.setdefault(canonical_key(kernel), []).append(kernel.name)

    groups = sorted(
        (names for names in buckets.values() if len(names) > 1), key=lambda ns: ns[0]
    )

    return len(kernels), len(buckets), groups


def _main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Parse and canonicalise emitted LSSEFT-analytic kernels."
    )
    parser.add_argument(
        "tree",
        nargs="?",
        help="an emitted autogenerated/ directory (or kernel_integrands.cpp)",
    )
    parser.add_argument(
        "--dedup",
        action="store_true",
        help="report how many emitted kernels are algebraically distinct",
    )
    parser.add_argument(
        "--counterterm-map",
        metavar="RUN.LOG",
        help=("print the run log's ** COUNTERTERM MAP section with each entry's print order "
              "canonicalised and the lines sorted -- comparable between runs despite I-01"),
    )
    parser.add_argument(
        "--show",
        metavar="kerNNN",
        help="print the canonical form of one kernel's value_ expression",
    )
    parser.add_argument(
        "--expect",
        metavar="EMITTED:DISTINCT:PAIRS",
        help="assert the --dedup numbers, e.g. 101:95:6; exit 1 if they differ",
    )
    parser.add_argument("--quiet", action="store_true", help="suppress progress output")
    args = parser.parse_args(argv)

    if args.counterterm_map:
        for line in canonical_counterterm_map(args.counterterm_map):
            print(line)
        return 0

    if not args.tree:
        parser.error("a tree is required unless --counterterm-map is given")

    if args.show:
        kernels = {k.name: k for k in extract_kernels(args.tree)}
        if args.show not in kernels:
            print(f"no kernel named {args.show} in {args.tree}", file=sys.stderr)
            return 2
        kernel = kernels[args.show]
        print(f"{args.show}  value_ (canonical):")
        print(f"  {canonical(parse_exact_no_floats(kernel.value))}")
        print(f"{args.show}  Wick_ (parsed):")
        print(f"  {parse_exact_no_floats(kernel.wick)}")
        return 0

    if not args.dedup:
        parser.error("nothing to do: pass --dedup, --show or --counterterm-map")

    emitted, distinct, groups = dedup_report(args.tree, verbose=not args.quiet)

    print(f"tree:     {_resolve(args.tree)}")
    print(f"emitted:  {emitted}")
    print(f"distinct after cancel(together(.)), keyed with Wick_: {distinct}")
    print(f"duplicate groups: {len(groups)}")
    for names in groups:
        print(f"  {' == '.join(names)}")

    collapsed = emitted - distinct
    print(f"kernels collapsed by dedup: {collapsed}")

    if args.expect:
        try:
            want = tuple(int(part) for part in args.expect.split(":"))
        except ValueError:
            print(f"--expect: cannot parse {args.expect!r}", file=sys.stderr)
            return 2
        if len(want) != 3:
            print("--expect wants EMITTED:DISTINCT:PAIRS", file=sys.stderr)
            return 2
        got = (emitted, distinct, len(groups))
        if got != want:
            print(f"\nFAIL: expected {want}, got {got}")
            return 1
        print(f"\nOK: matches --expect {want}")

    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
