#!/usr/bin/env bash
#
# validation/check_determinism.sh
#
# Regression test for issue I-01 (prompts/pre-python-migration-fixes/03-determinism.md).
#
# Runs the same binary, with the same flags, five times into five separate directories, and
# checks that the emitted `autogenerated/` tree is byte-identical across all five runs --
# excluding `pipeline_id.cpp` (whose entire body is a generation timestamp) and the
# `// Generated at ...` header line every other file carries (also a timestamp; see
# backends/LSSEFT.cpp:619,1534). This is the acceptance test prompt 03 was written against:
# before that prompt, 10 of 22 files varied between identical runs (see
# validation/NONDETERMINISM.md); after it, all 21 non-timestamp files are expected to agree.
#
# It also reports the counterterm map's two forms separately, because they are NOT expected to
# behave the same way:
#   - the raw (sorted-lines) form is NOT expected to be byte-stable -- GiNaC's own default-print
#     operand order inside each `-> mu^N = <expr>` line is process-random and is not reachable by
#     sorting our own containers (see NONDETERMINISM.md Sec 3.2 and the "counterterm map" section
#     of logs/03-determinism.md). This is reported for information, not as a pass/fail gate.
#   - the print-order-canonicalised form (validation/canonical_form.py --counterterm-map) IS
#     expected to be byte-stable, and IS gated.
#
# Usage:
#   validation/check_determinism.sh [build-dir]
#
# build-dir defaults to <repo-root>/build-validation (the default produced by
# validation/build.sh), which must already exist and be built -- this script does not build.
#
# Exit status: 0 if every gated check passes, 1 otherwise. A temporary working directory holding
# the five runs is created under the system temp directory and removed on exit unless KEEP=1 is
# set in the environment (in which case its path is printed).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUILD_DIR="${1:-${REPO_ROOT}/build-validation}"
BINARY="${BUILD_DIR}/LSSEFT_analytic"

if [[ ! -x "${BINARY}" ]]; then
  echo "check_determinism.sh: no binary at ${BINARY} -- run validation/build.sh first" >&2
  exit 1
fi

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lsseft-determinism.XXXXXX")"
cleanup() {
  if [[ "${KEEP:-0}" == "1" ]]; then
    echo "check_determinism.sh: KEEP=1 set, leaving ${WORK_DIR} in place"
  else
    rm -rf "${WORK_DIR}"
  fi
}
trap cleanup EXIT

echo "check_determinism.sh: binary   ${BINARY}"
echo "check_determinism.sh: work dir ${WORK_DIR}"
echo "check_determinism.sh: running five independent, identically-configured invocations ..."

for i in 1 2 3 4 5; do
  OUT="${WORK_DIR}/run${i}"
  LOG="${WORK_DIR}/run${i}.log"
  "${BINARY}" --no-auto-symmetrize --symmetrize-22 --counterterms --output "${OUT}" \
    > "${LOG}" 2>&1
  echo "  run ${i}: done"
done

# ---------------------------------------------------------------------------------------------
# per-file comparison across the five autogenerated/ trees
# ---------------------------------------------------------------------------------------------

FAIL=0
FILES=$(cd "${WORK_DIR}/run1/autogenerated" && ls)

echo
echo "check_determinism.sh: per-file comparison (stripping '// Generated at ...', excluding pipeline_id.cpp)"

for f in ${FILES}; do
  if [[ "${f}" == "pipeline_id.cpp" ]]; then
    continue
  fi

  first_md5=""
  distinct=0
  for i in 1 2 3 4 5; do
    m=$(grep -v '^// Generated at' "${WORK_DIR}/run${i}/autogenerated/${f}" | md5 -q 2>/dev/null \
        || grep -v '^// Generated at' "${WORK_DIR}/run${i}/autogenerated/${f}" | md5sum | cut -d' ' -f1)
    if [[ -z "${first_md5}" ]]; then
      first_md5="${m}"
    elif [[ "${m}" != "${first_md5}" ]]; then
      distinct=1
    fi
  done

  if [[ "${distinct}" == "0" ]]; then
    printf "  PASS  %s\n" "${f}"
  else
    printf "  FAIL  %s  (differs across the five runs)\n" "${f}"
    FAIL=1
  fi
done

# pipeline_id.cpp: expected to differ (it is a pure timestamp) -- report, do not gate
pid_distinct=0
pid_first=""
for i in 1 2 3 4 5; do
  m=$(md5 -q "${WORK_DIR}/run${i}/autogenerated/pipeline_id.cpp" 2>/dev/null \
      || md5sum "${WORK_DIR}/run${i}/autogenerated/pipeline_id.cpp" | cut -d' ' -f1)
  if [[ -z "${pid_first}" ]]; then
    pid_first="${m}"
  elif [[ "${m}" != "${pid_first}" ]]; then
    pid_distinct=1
  fi
done
if [[ "${pid_distinct}" == "1" ]]; then
  echo "  INFO  pipeline_id.cpp  (differs across the five runs, as expected -- it is a pure timestamp, not gated)"
else
  echo "  INFO  pipeline_id.cpp  (identical across the five runs -- unexpected, but harmless)"
fi

# ---------------------------------------------------------------------------------------------
# counterterm map: raw (informational only) and print-order-canonicalised (gated)
# ---------------------------------------------------------------------------------------------

echo
echo "check_determinism.sh: counterterm map"

raw_first=""
raw_distinct=0
for i in 1 2 3 4 5; do
  m=$(awk '/\*\* COUNTERTERM MAP/{flag=1} flag' "${WORK_DIR}/run${i}.log" \
        | sed -E $'s/\x1b\[[0-9;]*m//g' | sort | md5 -q 2>/dev/null \
      || awk '/\*\* COUNTERTERM MAP/{flag=1} flag' "${WORK_DIR}/run${i}.log" \
        | sed -E $'s/\x1b\[[0-9;]*m//g' | sort | md5sum | cut -d' ' -f1)
  if [[ -z "${raw_first}" ]]; then
    raw_first="${m}"
  elif [[ "${m}" != "${raw_first}" ]]; then
    raw_distinct=1
  fi
done
if [[ "${raw_distinct}" == "1" ]]; then
  echo "  INFO  raw sorted-lines form differs across the five runs (expected -- GiNaC's own"
  echo "        default-print operand order is process-random and not fixable from our side;"
  echo "        see validation/NONDETERMINISM.md; not gated)"
else
  echo "  INFO  raw sorted-lines form identical across the five runs (better than expected, harmless)"
fi

canon_first=""
canon_distinct=0
for i in 1 2 3 4 5; do
  m=$(python3 "${SCRIPT_DIR}/canonical_form.py" --counterterm-map "${WORK_DIR}/run${i}.log" \
        | md5 -q 2>/dev/null \
      || python3 "${SCRIPT_DIR}/canonical_form.py" --counterterm-map "${WORK_DIR}/run${i}.log" \
        | md5sum | cut -d' ' -f1)
  if [[ -z "${canon_first}" ]]; then
    canon_first="${m}"
  elif [[ "${m}" != "${canon_first}" ]]; then
    canon_distinct=1
  fi
done
if [[ "${canon_distinct}" == "0" ]]; then
  echo "  PASS  print-order-canonicalised form identical across the five runs"
else
  echo "  FAIL  print-order-canonicalised form differs across the five runs"
  FAIL=1
fi

echo
if [[ "${FAIL}" == "0" ]]; then
  echo "check_determinism.sh: RESULT: PASS -- all gated checks agree across five independent runs"
else
  echo "check_determinism.sh: RESULT: FAIL -- see FAIL lines above"
fi

exit "${FAIL}"
