#!/usr/bin/env python3
"""validation/compare_autogenerated.py -- functional comparison of two emitted trees.

    validation/compare_autogenerated.py A/autogenerated B/autogenerated

Answers one question: **do these two `autogenerated/` trees define the same set of integrands,
as functions?**  Exit status 0 on match, 1 on mismatch, 2 on usage/parse error.

Why not `diff`
--------------
`diff` on the generated tree is not a usable regression test.  GiNaC 1.8.10 seeds its expression
hash from a runtime address, so the operand ordering inside printed expressions varies *between
processes*; `one_loop_element_key::hash()` and `LSSEFT_kernel::hash()` hash default-printed
strings, those hashes key two `std::unordered_map`s, and those maps drive kernel naming and file
emission order.  Two runs of the same binary with identical flags produce different
`kernel_integrands.cpp` files.  See validation/NONDETERMINISM.md.

So the comparison here is deliberately insensitive to both kernel renumbering and GiNaC term
order:

  1. Extract each kernel's `value_` and `Wick_` expression (validation/canonical_form.py).
  2. Parse them into SymPy with **exact rational literals** -- no binary floats, hence no 1e-16
     residuals masquerading as algebraic disagreements.
  3. Substitute a surrogate power spectrum for `data_->Pk(.)` and drop the `Mpc_units::*` unit
     factors (they cancel identically on both sides).
  4. Evaluate at a fixed set of seeded pseudo-random exact-rational `(k_, q_, z_)` points, in
     mpmath at high precision, giving each kernel a *signature vector*.
  5. Compare the **multisets** of signature vectors -- not the per-kernel mapping.

The `compute_*` name set of `Pk_expressions.cpp` is compared as well, since the signatures cover
the kernels but not the assembly layer above them.

Baseline archive
----------------
`--emit-signatures FILE` serialises the signature multiset (with the seed and the points) so
that later prompts can compare against the *stored* pre-fix signatures without re-running the
pre-fix code.  `--signatures FILE` compares a tree against such a file instead of against a
second tree.

See validation/README.md and
prompts/pre-python-migration-fixes/02-oracle-harness-and-baseline.md.
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import random
import sys
from typing import Dict, List, NamedTuple, Sequence, Tuple

import mpmath
import sympy

# canonical_form.py is the shared parsing layer and lives alongside this file. Make the import
# work regardless of the caller's working directory.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import canonical_form  # noqa: E402
from canonical_form import FREE_SYMBOLS, PK  # noqa: E402

# =============================================================================================
# Evaluation-point policy.  EVERY LATER PROMPT DEPENDS ON THESE BEING STABLE.
#
# Changing any constant in this block invalidates every stored signature file, including
# validation/baselines/pre-fix/signatures.json.  If you must change one, re-baseline and say so
# in the campaign log.
# =============================================================================================

#: RNG seed.  `random.Random(SEED).randrange(...)` -- integer draws from the Mersenne Twister,
#: which are stable across CPython versions (unlike, say, `random.random()` rounding or
#: `random.sample` internals).  The points are therefore reproducible from the seed alone.
SEED = 20260904

#: Number of (k_, q_, z_) points.  The study found 25 sufficient; this is the floor it names.
N_POINTS = 25

#: Common denominator of every sampled coordinate.  Prime, so that the exact-rational points
#: share no factor with the small integer coefficients in the emitted kernels and cannot
#: accidentally cancel a term away.
DEN = 1000003

#: Sampling ranges, as numerator bounds over DEN (inclusive lo, exclusive hi):
#:   k_ in [0.05, 1.0)   -- external momentum
#:   q_ in [0.05, 5.0)   -- loop momentum, straddling k_ so that both q_ < k_ and q_ > k_ occur
#:   z_ in [-0.9, 0.9)   -- cos(angle); the emitted code has z_ = 2*x_[1] - 1 in [-1, 1], and we
#:                          stay off the endpoints so that (q_^2 + k_^2 - 2 q_ k_ z_), which is
#:                          the denominator of nearly every kernel, cannot come near zero.
K_RANGE = (DEN // 20, DEN)
Q_RANGE = (DEN // 20, 5 * DEN)
Z_RANGE = (-9 * DEN // 10, 9 * DEN // 10)

#: Working precision for the numeric evaluation.
DPS = 60

#: Significant digits retained in a signature's bucket key.  Two trees that emit the same
#: expression modulo GiNaC term order parse to *structurally identical* SymPy objects, so their
#: lambdified evaluations agree bit-for-bit; 25 digits out of 60 is a wide margin.
SIG_DIGITS = 25

#: Relative tolerance for the fallback pairing pass, used only for signatures that the exact
#: bucket keys failed to pair.  Reported in the output whenever it is exercised.
REL_TOL = mpmath.mpf(10) ** -20

#: Surrogate power spectrum substituted for `data_->Pk(.)`.  A positive rational function on
#: x > 0 decaying like x^-3, so it has roughly the shape of a real P(k) without introducing any
#: irrational constant of its own.  Its precise form is irrelevant to the comparison -- it only
#: has to be the same on both sides and non-degenerate.
_PK_ARG = sympy.Symbol("_pk_arg")
PK_SURROGATE = _PK_ARG / (1 + 3 * _PK_ARG**2 + 7 * _PK_ARG**4)

#: Guard: reject a sampled point at which the common kernel denominator is this small.
_DENOM_FLOOR = sympy.Rational(1, 10**6)


def evaluation_points(
    seed: int = SEED, n_points: int = N_POINTS
) -> List[Tuple[sympy.Rational, sympy.Rational, sympy.Rational]]:
    """The fixed list of exact-rational (k_, q_, z_) points, derived from `seed` alone."""

    rng = random.Random(seed)
    points: List[Tuple[sympy.Rational, sympy.Rational, sympy.Rational]] = []

    while len(points) < n_points:
        k = sympy.Rational(rng.randrange(*K_RANGE), DEN)
        q = sympy.Rational(rng.randrange(*Q_RANGE), DEN)
        z = sympy.Rational(rng.randrange(*Z_RANGE), DEN)

        # q^2 + k^2 - 2 q k z is |q - k|^2 in the loop; it is the denominator of nearly every
        # emitted kernel and the argument of the sqrt in nearly every Wick product.
        if q * q + k * k - 2 * q * k * z < _DENOM_FLOOR:
            continue

        points.append((k, q, z))

    return points


# =============================================================================================
# signatures
# =============================================================================================


class Signature(NamedTuple):
    """One kernel's functional fingerprint."""

    name: str  #: kerNNN, kept only for reporting -- never for matching
    key: Tuple[str, ...]  #: 2 * N_POINTS rounded decimal strings: value_ then Wick_
    raw: Tuple[mpmath.mpf, ...]  #: the same numbers, unrounded, for the tolerance fallback


def _substitute_surrogate(expr: sympy.Expr) -> sympy.Expr:
    """Replace every `Pk(arg)` by the surrogate power spectrum evaluated at `arg`."""

    calls = [a for a in expr.atoms(sympy.Function) if a.func == PK]
    if not calls:
        return expr
    return expr.xreplace(
        {call: PK_SURROGATE.subs(_PK_ARG, call.args[0]) for call in calls}
    )


def _round(value: mpmath.mpf) -> str:
    """A bucket key for one number: `SIG_DIGITS` significant digits, canonically formatted."""

    return mpmath.nstr(value, SIG_DIGITS, strip_zeros=False, min_fixed=0, max_fixed=0)


def signatures(
    tree: str,
    points: Sequence[Tuple[sympy.Rational, sympy.Rational, sympy.Rational]],
    label: str = "",
    verbose: bool = True,
) -> List[Signature]:
    """Compute one signature per emitted kernel in `tree`."""

    kernels = canonical_form.extract_kernels(tree)

    mp_points = [
        tuple(mpmath.mpf(r.p) / mpmath.mpf(r.q) for r in point) for point in points
    ]

    out: List[Signature] = []
    for index, kernel in enumerate(kernels, start=1):
        if verbose and (index % 25 == 0 or index == len(kernels)):
            print(
                f"  [{label}] evaluated {index}/{len(kernels)} kernels",
                file=sys.stderr,
                flush=True,
            )

        raw: List[mpmath.mpf] = []
        for which, text in (("value_", kernel.value), ("Wick_", kernel.wick)):
            expr = _substitute_surrogate(canonical_form.parse_exact_no_floats(text))
            try:
                fn = sympy.lambdify(FREE_SYMBOLS, expr, "mpmath")
            except Exception as exc:  # pragma: no cover -- emitter shape change
                raise ValueError(
                    f"{tree}: cannot lambdify {kernel.name} {which}: {exc}"
                ) from exc
            for mp_point in mp_points:
                raw.append(mpmath.mpf(fn(*mp_point)))

        out.append(
            Signature(
                name=kernel.name,
                key=tuple(_round(v) for v in raw),
                raw=tuple(raw),
            )
        )

    return out


def _close(a: Sequence[mpmath.mpf], b: Sequence[mpmath.mpf]) -> bool:
    """Componentwise relative agreement to REL_TOL (absolute, near zero)."""

    for x, y in zip(a, b):
        scale = max(abs(x), abs(y))
        if scale == 0:
            continue
        if abs(x - y) / scale > REL_TOL:
            return False
    return True


# =============================================================================================
# comparison
# =============================================================================================


class Result(NamedTuple):
    matched: int
    only_a: List[Signature]
    only_b: List[Signature]
    fallback_pairs: int


def compare_signatures(
    left: Sequence[Signature], right: Sequence[Signature]
) -> Result:
    """Multiset comparison of two signature lists.

    Pass 1 pairs signatures whose rounded bucket keys are identical.  Pass 2 tries to pair the
    residue within REL_TOL, so that a difference in *representation* (a legitimately different
    but algebraically equal printed form) is not reported as a difference in *function*.
    """

    left_by_key: Dict[Tuple[str, ...], List[Signature]] = collections.defaultdict(list)
    right_by_key: Dict[Tuple[str, ...], List[Signature]] = collections.defaultdict(list)
    for sig in left:
        left_by_key[sig.key].append(sig)
    for sig in right:
        right_by_key[sig.key].append(sig)

    matched = 0
    residue_left: List[Signature] = []
    residue_right: List[Signature] = []

    for key in set(left_by_key) | set(right_by_key):
        ls, rs = left_by_key.get(key, []), right_by_key.get(key, [])
        common = min(len(ls), len(rs))
        matched += common
        residue_left.extend(ls[common:])
        residue_right.extend(rs[common:])

    fallback = 0
    remaining_right = list(residue_right)
    still_left: List[Signature] = []
    for lsig in residue_left:
        hit = next(
            (i for i, rsig in enumerate(remaining_right) if _close(lsig.raw, rsig.raw)),
            None,
        )
        if hit is None:
            still_left.append(lsig)
        else:
            remaining_right.pop(hit)
            matched += 1
            fallback += 1

    return Result(
        matched=matched,
        only_a=sorted(still_left, key=lambda s: s.name),
        only_b=sorted(remaining_right, key=lambda s: s.name),
        fallback_pairs=fallback,
    )


# =============================================================================================
# serialisation
# =============================================================================================


def dump_signatures(
    path: str, sigs: Sequence[Signature], source: str, seed: int, n_points: int
) -> None:
    payload = {
        "format": "LSSEFT-analytic integrand signature multiset, v1",
        "produced_by": "validation/compare_autogenerated.py",
        "source_tree": source,
        "seed": seed,
        "n_points": n_points,
        "denominator": DEN,
        "k_range": list(K_RANGE),
        "q_range": list(Q_RANGE),
        "z_range": list(Z_RANGE),
        "mpmath_dps": DPS,
        "sig_digits": SIG_DIGITS,
        "surrogate_Pk": str(PK_SURROGATE).replace(str(_PK_ARG), "x"),
        "points": [
            {"k_": f"{k.p}/{k.q}", "q_": f"{q.p}/{q.q}", "z_": f"{z.p}/{z.q}"}
            for k, q, z in evaluation_points(seed, n_points)
        ],
        "kernel_count": len(sigs),
        "signatures": sorted(
            [{"name": s.name, "key": list(s.key)} for s in sigs],
            key=lambda entry: entry["key"],
        ),
    }
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=1, sort_keys=False)
        handle.write("\n")


def load_signatures(path: str) -> Tuple[List[Signature], dict]:
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)

    for field, expected in (
        ("seed", SEED),
        ("n_points", N_POINTS),
        ("denominator", DEN),
        ("sig_digits", SIG_DIGITS),
    ):
        if payload.get(field) != expected:
            raise ValueError(
                f"{path}: stored {field}={payload.get(field)!r} but this script uses "
                f"{expected!r}; the evaluation-point policy changed and the stored "
                "signatures are not comparable. Re-baseline, and record it in the log."
            )

    sigs = [
        Signature(
            name=entry["name"],
            key=tuple(entry["key"]),
            raw=tuple(mpmath.mpf(s) for s in entry["key"]),
        )
        for entry in payload["signatures"]
    ]
    return sigs, payload


# =============================================================================================
# main
# =============================================================================================


def _compare_names(a: str, b: str, label_a: str, label_b: str) -> bool:
    try:
        names_a = canonical_form.compute_names(a)
        names_b = canonical_form.compute_names(b)
    except FileNotFoundError as exc:
        print(f"compute_* name comparison skipped: {exc}")
        return True

    print(f"compute_* names: {label_a} {len(names_a)}, {label_b} {len(names_b)}")
    if names_a == names_b:
        print(f"compute_* name sets: IDENTICAL ({len(names_a)} names)")
        return True

    only_a = sorted(set(names_a) - set(names_b))
    only_b = sorted(set(names_b) - set(names_a))
    print("compute_* name sets: DIFFER")
    for name in only_a:
        print(f"  only in {label_a}: {name}")
    for name in only_b:
        print(f"  only in {label_b}: {name}")
    return False


def _main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Compare two emitted autogenerated/ trees as functions."
    )
    parser.add_argument("left", help="first autogenerated/ directory")
    parser.add_argument(
        "right",
        nargs="?",
        help="second autogenerated/ directory (omit when using --signatures)",
    )
    parser.add_argument(
        "--signatures",
        metavar="FILE",
        help="compare `left` against a stored signature file instead of a second tree",
    )
    parser.add_argument(
        "--emit-signatures",
        metavar="FILE",
        help="write `left`'s signature multiset to FILE (for the baseline archive)",
    )
    parser.add_argument("--seed", type=int, default=SEED, help=f"RNG seed (default {SEED})")
    parser.add_argument(
        "--points", type=int, default=N_POINTS, help=f"number of points (default {N_POINTS})"
    )
    parser.add_argument("--quiet", action="store_true", help="suppress progress output")
    args = parser.parse_args(argv)

    if args.right is None and not (args.signatures or args.emit_signatures):
        parser.error("give a second tree, or --signatures FILE, or --emit-signatures FILE")
    if args.right is not None and args.signatures:
        parser.error("--signatures compares against a file; do not also give a second tree")

    mpmath.mp.dps = DPS
    verbose = not args.quiet

    points = evaluation_points(args.seed, args.points)
    print("validation/compare_autogenerated.py")
    print(f"  seed             {args.seed}")
    print(f"  points           {len(points)} exact-rational (k_, q_, z_) triples")
    print(f"  precision        mpmath dps = {DPS}; signature key = {SIG_DIGITS} sig. digits")
    print(f"  fallback rel tol {mpmath.nstr(REL_TOL, 3)}")
    print(f"  surrogate P(k)   {str(PK_SURROGATE).replace(str(_PK_ARG), 'k')}")
    print()

    label_a = args.left
    sigs_a = signatures(args.left, points, label="A", verbose=verbose)
    print(f"A  {label_a}")
    print(f"   kernels: {len(sigs_a)}")

    if args.emit_signatures and not (args.right or args.signatures):
        dump_signatures(
            args.emit_signatures, sigs_a, args.left, args.seed, args.points
        )
        print(f"\nwrote {len(sigs_a)} signatures to {args.emit_signatures}")
        return 0

    if args.signatures:
        sigs_b, payload = load_signatures(args.signatures)
        label_b = f"{args.signatures} (stored: {payload.get('source_tree')})"
        names_ok = True
        print(f"B  {label_b}")
        print(f"   kernels: {len(sigs_b)}")
    else:
        sigs_b = signatures(args.right, points, label="B", verbose=verbose)
        label_b = args.right
        print(f"B  {label_b}")
        print(f"   kernels: {len(sigs_b)}")
        print()
        names_ok = _compare_names(args.left, args.right, "A", "B")

    if args.emit_signatures:
        dump_signatures(args.emit_signatures, sigs_a, args.left, args.seed, args.points)
        print(f"wrote {len(sigs_a)} signatures to {args.emit_signatures}")

    print()
    result = compare_signatures(sigs_a, sigs_b)
    print(f"signatures matched: {result.matched} of {len(sigs_a)} (A) / {len(sigs_b)} (B)")
    if result.fallback_pairs:
        print(
            f"  of which {result.fallback_pairs} paired only via the "
            f"rel-tol {mpmath.nstr(REL_TOL, 3)} fallback, not by exact key"
        )

    ok = names_ok and not result.only_a and not result.only_b

    if result.only_a or result.only_b:
        print()
        print(f"MISMATCH: {len(result.only_a)} signature(s) only in A, "
              f"{len(result.only_b)} only in B")
        for sig in result.only_a:
            print(f"  only in A: {sig.name}")
            print(f"    first 3 components: {', '.join(sig.key[:3])}")
        for sig in result.only_b:
            print(f"  only in B: {sig.name}")
            print(f"    first 3 components: {', '.join(sig.key[:3])}")
        print()
        print("The two trees are NOT functionally equivalent. The kerNNN labels above are the")
        print("emitted names carrying the unmatched signatures; inspect their `double value_`")
        print("and `double Wick_` lines in each tree's kernel_integrands.cpp.")

    print()
    if ok:
        print("RESULT: MATCH -- the two trees define the same integrands as functions.")
        return 0
    print("RESULT: MISMATCH")
    return 1


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
